include /etc/nginx/conf.d/upstream.inc; # 백엔드 변수 쓰려고 include 해준 거임

server {
    listen 80;  # 80번 포트로 인입되는 클라이언트 기본 접속 수신

    location / {    
        proxy_pass http://backend;      # 'backend' 업스트림 그룹으로 트래픽
        proxy_set_header Host $host;    # 클라이언트의 원본 호스트 IP를 온전히 전달
    }
}